"""Initial migration

Revision ID: dd7124a271fb
Revises: 5dc4f9c0fb83
Create Date: 2025-04-10 10:16:04.938500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd7124a271fb'
down_revision = '5dc4f9c0fb83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
